import type { Metadata } from "next";
import { Inter, Calistoga } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({
  variable: "--font-inter",
  display: "swap",
  subsets: ["latin"],
});

const calistoga = Calistoga({
  variable: "--font-calistoga",
  display: "swap",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pixel to Prod",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${calistoga.variable} antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
